import config from "./imports";
import globalConfig from "../../app/data";
const buttonLabels = { ...globalConfig.buttonLabels };

const TextData = {
  year: "year",
  plates: "Plates",
  rotate: "Rotate",
  submit: "Submit",
  label: "Show Labels",
  selected: "selected",
  continent: "Continent",
  timePeriod: "Time Period",
  notSelected: "not selected",
  yearAgo: "Million Years Ago",
  canvas: "Canvas area with fixed ",
  resetLiveText: globalConfig.resetLiveText,
  resetPopupText: globalConfig.resetPopupText,
  ...buttonLabels,
  rotateAlt: "Rotate button to rotate the plate 90 degree anti clockwise",
  startScreenInfo: [
    "Examine fossils and rock records found across continents to try and piece together the movement of the continents throughout Earth’s history.",
    "Select plates from the right. Drag the plates to the map grid area on the left to recreate Earth. You can rotate the plates to align them properly.",
  ],
  infoText:
    "Assemble the continental plates to recreate how Earth looked at the chosen time period. You can change the time period using the buttons. Drag and rotate the plates to align. Use Reset to start all over again.",

  completionPopup: {
    ...globalConfig.completionPopup,
    content: "You have recreated Earth for all of the time periods.",
  },
  toastMsg: {
    correct: globalConfig.correctToastMessage,
    incorrect: globalConfig.incorrectToastMessage,
    final200:
      "<strong>Well done!</strong> You have successfully recreated Earth from 200 million years ago.",
    final150:
      "<strong>Well done!</strong> You have successfully recreated Earth from 150 million years ago.",
    final100:
      "<strong>Well done!</strong> You have successfully recreated Earth from 100 million years ago.",
  },
  200: {
    id: 200,
    keys: [
      {
        img: config.triassicCoalBed,
        text: "Triassic Coal Bed",
        description: "Legend denoting Triassic coal bed",
      },
      {
        img: config.triassicShale,
        text: "Triassic Shale",
        description: "Legend denoting Triassic-era shale",
      },
      {
        img: config.halideDeposit,
        text: "Halide Deposit",
        description: "Legend denoting halide deposit",
      },
      {
        img: config.fossilRemainsofLystrosaurus,
        text: "Fossil Remains of Lystrosaurus",
        description: "Legend denoting fossil remains of Lystrosaurus",
      },
    ],
    southAmerica: {
      serialNo: 0,
      label: "South America",
      className: "southAmerica",
      thumbData: config.thumb_200_1,
      svgData: config.svg_200_1,
      desc: "South American plate. A thin halide deposit strip found across the top of the plate. Lystrosaurus fossil remains cover the bottom half of the plate",
    },
    northAmerica: {
      serialNo: 1,
      label: "North America",
      className: "northAmerica",
      thumbData: config.thumb_200_2,
      svgData: config.svg_200_2,
      desc: "North American plate. Halide deposit on the bottom. Triassic coal bed runs southeast above the halide. Triassic shale strip runs along eastern coast",
    },
    africa: {
      serialNo: 2,
      label: "Africa",
      className: "africa",
      thumbData: config.thumb_200_3,
      svgData: config.svg_200_3,
      desc: "African plate. Triassic coal bed on top western ⅓. Strip of halide deposit below coal runs across plate. Lystrosaurus fossil remains cover bottom ⅓",
    },
    eurasia: {
      serialNo: 3,
      label: "Eurasia",
      className: "eurasia",
      thumbData: config.thumb_200_4,
      svgData: config.svg_200_4,
      desc: "Eurasian tectonic plate. A thin strip of Triassic-era shale runs across the middle of the plate",
    },
    australia: {
      serialNo: 4,
      label: "Australia",
      className: "australia",
      thumbData: config.thumb_200_5,
      svgData: config.svg_200_5,
      desc: "Australian tectonic plate. Halide deposit on the west coast. Lystrosaurus fossil remains found on the eastern half of the plate",
    },
    antarctica: {
      serialNo: 5,
      label: "Antarctica",
      className: "antarctica",
      thumbData: config.thumb_200_6,
      svgData: config.svg_200_6,
      desc: "Antarctic tectonic plate. Lystrosaurus fossil remains cover the bottom ¾ of the plate",
    },
    india: {
      serialNo: 6,
      label: "India",
      className: "india",
      thumbData: config.thumb_200_7,
      svgData: config.svg_200_7,
      desc: "Indian tectonic plate. A strip of halide deposit is found on the bottom ⅓ of the plate",
    },
  },
  150: {
    id: 150,
    keys: [
      {
        img: config.jurrasaicEraShale,
        text: "Jurassic Era Shale",
        description: "Legend denoting Jurassic-era shale",
      },
      {
        img: config.halideDeposit,
        text: "Halide Deposit",
        description: "Legend denoting halide deposit",
      },
      {
        img: config.graniteDeposi,
        text: "Granite Deposit",
        description: "Legend denoting granite deposit",
      },
      {
        img: config.jurassicEraOilDeposits,
        text: "Jurassic Era Oil Deposits",
        description: "Legend denoting Jurassic-era oil deposits",
      },
      {
        img: config.fossilRemainsofMesosauru,
        text: "Fossil Remains of Mesosaurus",
        description: "Legend denoting fossil remains of Mesosaurus",
      },
    ],
    madagascar: {
      serialNo: 0,
      label: "Madagascar",
      className: "madagascar",
      thumbData: config.thumb_150_6,
      svgData: config.svg_150_6,
      desc: "Madagascar tectonic plate. Jurassic-era shale covers the top ½ of the plate. Mesosaurus fossil remains are found across the bottom ½ of the plate",
    },
    southAmerica: {
      serialNo: 1,
      label: "South America",
      className: "southAmerica",
      thumbData: config.thumb_150_1,
      svgData: config.svg_150_1,
      desc: "South American plate. Halide deposit strip at top ⅓ of plate from east coast. Mesosaurus fossils underneath halide. Granite deposit strip near bottom",
    },
    africa: {
      serialNo: 2,
      label: "Africa",
      className: "africa",
      thumbData: config.thumb_150_2,
      svgData: config.svg_150_2,
      desc: "African plate. Jurassic oil north. In lower ½, halide deposit west and Jurassic-era shale east. Mesosaurus fossils under shale; granite deposit south",
    },
    australia: {
      serialNo: 3,
      label: "Australia",
      className: "australia",
      thumbData: config.thumb_150_3,
      svgData: config.svg_150_3,
      desc: "Australian tectonic plate. Mesosaurus fossil remains found in the eastern half of the plate",
    },
    antarctica: {
      serialNo: 4,
      label: "Antarctica",
      className: "antarctica",
      thumbData: config.thumb_150_4,
      svgData: config.svg_150_4,
      desc: "Antarctic tectonic plate. Jurassic-era shale found in the north. Fossil remains of Mesosaurus run in a curved strip through the middle of the plate",
    },
    india: {
      serialNo: 5,
      label: "India",
      className: "india",
      thumbData: config.thumb_150_5,
      svgData: config.svg_150_5,
      desc: "Indian plate. Jurassic-era shale in a curved strip across bottom ⅓. Mesosaurus fossil remains found underneath shale and cover southern tip of plate",
    },

    northAmerica: {
      serialNo: 6,
      label: "North America",
      className: "northAmerica",
      thumbData: config.thumb_150_7,
      svgData: config.svg_150_7,
      desc: "North American tectonic plate. Jurassic-era oil deposits found across the southern ¼ of the plate. Jurassic-era shale found in the northeast",
    },
    eurasia: {
      serialNo: 7,
      label: "Eurasia",
      className: "eurasia",
      thumbData: config.thumb_150_8,
      svgData: config.svg_150_8,
      desc: "Eurasian plate. Jurassic-era oil deposits found across southwestern coast. Strip of Jurassic-era shale found in the center of western side of plate",
    },
  },
  100: {
    id: 100,
    keys: [
      {
        img: config.fossilRemainsofDonwelliacaulischlouberii,
        text: "Fossil Remains of Donwelliacaulis chlouberii",
        description:
          "Legend denoting fossil remains of Donwelliacaulis chlouberii ",
      },
      {
        img: config.cretaceousNaturalGasDeposit,
        text: "Cretaceous Natural Gas Deposit",
        description: "Legend denoting Creataceous natural gas deposit",
      },
      {
        img: config.cretaceousEraShale,
        text: "Cretaceous Era Shale",
        description: "Legend denoting Cretaceous-era shale",
      },
      {
        img: config.earlyPrimateFossils,
        text: "Early Primate Fossils",
        description: "Legend denoting early primate fossils",
      },
      {
        img: config.cretaceousLimestone,
        text: "Cretaceous Limestone",
        description: "Legend denoting Cretaceous limestone",
      },
    ],
    madagascar: {
      serialNo: 0,
      label: "Madagascar",
      className: "madagascar",
      thumbData: config.thumb_100_7,
      svgData: config.svg_100_7,
      desc: "Madagascar tectonic plate. Early primate fossils found in the center of the plate along the eastern half",
    },
    india: {
      serialNo: 1,
      label: "India",
      className: "india",
      thumbData: config.thumb_100_8,
      svgData: config.svg_100_8,
      desc: "Indian tectonic plate. Early primate fossils found in the southwestern portion of plate",
    },
    africa: {
      serialNo: 2,
      label: "Africa",
      className: "africa",
      thumbData: config.thumb_100_1,
      svgData: config.svg_100_1,
      desc: "African tectonic plate. Cretaceous natural gas deposit found along the western coast",
    },
    eurasia: {
      serialNo: 3,
      label: "Eurasia",
      className: "eurasia",
      thumbData: config.thumb_100_2,
      svgData: config.svg_100_2,
      desc: "Eurasian tectonic plate. Fossil remains of Donwelliacaulis chlouberii found in the majority of the northwestern half of the plate",
    },
    antarctica: {
      serialNo: 4,
      label: "Antarctica",
      className: "antarctica",
      thumbData: config.thumb_100_3,
      svgData: config.svg_100_3,
      desc: "Antarctic tectonic plate. Cretaceous-era shale found across roughly half of the eastern part of the plate",
    },
    australia: {
      serialNo: 5,
      label: "Australia",
      className: "australia",
      thumbData: config.thumb_100_4,
      svgData: config.svg_100_4,
      desc: "Australian tectonic plate. Cretaceous-era shale found in a small portion of the southeastern part of the plate",
    },
    northAmerica: {
      serialNo: 6,
      label: "North America",
      className: "northAmerica",
      thumbData: config.thumb_100_5,
      svgData: config.svg_100_5,
      desc: "North American plate. Fossil remains of Donwelliacaulis chlouberii found in northeast. Cretaceous limestone found in center of bottom ⅓ of plate",
    },
    southAmerica: {
      serialNo: 7,
      label: "South America",
      className: "southAmerica",
      thumbData: config.thumb_100_6,
      svgData: config.svg_100_6,
      desc: "South American tectonic plate. Cretaceous natural gas deposit found in the northeastern part of the plate",
    },
  },
};

export default TextData;
